org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -Dsun.net.client.defaultConnectTimeout=60000 -Dsun.net.client.defaultReadTimeout=60000
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true
org.gradle.workers.max=4

systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=7890
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=7890
systemProp.http.nonProxyHosts=localhost|127.0.0.1
systemProp.http.keepAlive=false
systemProp.https.protocols=TLSv1.2,TLSv1.3
